language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest
